// <auto-generated />
using System;
using Com.A4aero.Ams.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Com.A4aero.Ams.DataModel.Migrations
{
    [DbContext(typeof(AmsContext))]
    [Migration("20190618034930_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Com.A4aero.Ams.DataModel.BusinessEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgentType");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("City");

                    b.Property<string>("Code");

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Country");

                    b.Property<DateTime>("CreatedOnUtc");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Email");

                    b.Property<string>("LoginUrl");

                    b.Property<string>("Logo");

                    b.Property<long>("MarkupPlanId");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("ReferredBy");

                    b.Property<string>("SMTPPassword");

                    b.Property<int>("SMTPPort");

                    b.Property<string>("SMTPServer");

                    b.Property<string>("SMTPUsername");

                    b.Property<string>("SecurityCode");

                    b.Property<string>("State");

                    b.Property<int>("Status");

                    b.Property<string>("Street");

                    b.Property<DateTime>("UpdatedOnUtc");

                    b.Property<string>("Zip");

                    b.HasKey("Id");

                    b.HasIndex("MarkupPlanId");

                    b.ToTable("BusinessEntities");
                });

            modelBuilder.Entity("Com.A4aero.Ams.DataModel.MarkupPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOnUtc");

                    b.Property<string>("MarkupPlanName");

                    b.Property<DateTime>("UpdatedOnUtc");

                    b.HasKey("Id");

                    b.ToTable("MarkupPlans");
                });

            modelBuilder.Entity("Com.A4aero.Ams.DataModel.BusinessEntity", b =>
                {
                    b.HasOne("Com.A4aero.Ams.DataModel.MarkupPlan", "MarkupPlan")
                        .WithMany("BusinessEntities")
                        .HasForeignKey("MarkupPlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
